package com.hitbosss.presentation.feature.settings

/** English tutorial content (authored translation of [tutorialDataEs]; not present in iOS). */
val tutorialDataEn: List<TutorialExercise> = listOf(
    TutorialExercise(
        apiKey = "officialPowerlifting", title = "Powerlifting", sport = "powerlifting",
        info = "Since our community is not mostly made up of athletes competing at a professional level, we have adjusted the thresholds to make them more accessible and motivating.\n\nThis ensures that the highest levels are not left empty and that there is clear, achievable progression for all users.",
        videoUrl = null,
        sections = listOf(
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 229 kg (505 lbs)\n• Noob: 230–339 kg (507–747 lbs)\n• Intermediate: 340–409 kg (750–902 lbs)\n• Advanced: 410 – 489 kg (904–1078 lbs)\n• Elite: 490 kg or more (1080 lbs or more)\n\n**Points score**\n• Beginner: up to 139 points\n• Noob: 140-209 points\n• Intermediate: 210-269 points\n• Advanced: 270-319 points\n• Elite: more than 320 points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 99 kg (218 lbs)\n• Noob: 100–169 kg (220–373 lbs)\n• Intermediate: 170–249 kg (375–549 lbs)\n• Advanced: 250–329 kg (551–725 lbs)\n• Elite: 330 kg or more (728 lbs or more)\n\n**Points score**\n• Beginner: up to 119 points\n• Noob: 120-189 points\n• Intermediate: 190-259 points\n• Advanced: 260-319 points\n• Elite: more than 320 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "squat", title = "Squat", sport = "powerlifting",
        info = "A fundamental exercise to build lower-body strength. It mainly involves the quads and glutes, and also activates the hamstrings and core.\n\nPerfect for measuring power, mobility and body control.\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, ensuring fairness, safety and real competition in the ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_Sentadilla.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• Feet fully planted on the floor.\n• Back straight throughout the movement.\n• The hips must break parallel (drop below the line of the knees).\n• Full extension on the way up (hips and knees locked at the end).\n• Bar placed on the traps or rear delts (depending on the variation).\n• No external assistance allowed.\n• It must be a single maximum repetition (1RM)."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one (same side, separated from each other and with sound).\n2. Show the weight engraved on the end of the bar.\n3. Record the execution from a side or diagonal angle, where you can clearly see:\n   - The depth of the movement.\n   - The placement of the bar.\n   - The full range of the lift."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 59 kg (130 lbs)\n• Noob: 60-99 kg (132-218 lbs)\n• Intermediate: 100-139 kg (220-306 lbs)\n• Advanced: 140-169 kg (309-373 lbs)\n• Elite: more than 170 kg (375 lbs)\n\n**Points score**\n• Beginner: up to 55 Points\n• Noob: 56-75 Points\n• Intermediate: 76-95 Points\n• Advanced: 96-110 Points\n• Elite: more than 111 Points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 34 kg (75 lbs)\n• Noob: 35-59 kg (77-130 lbs)\n• Intermediate: 60-89 kg (132-196 lbs)\n• Advanced: 90-119 kg (198-262 lbs)\n• Elite: more than 120 kg (265 lbs)\n\n**Points score**\n• Beginner: up to 40 Points\n• Noob: 41-65 Points\n• Intermediate: 66-90 Points\n• Advanced: 91-110 Points\n• Elite: more than 111 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "benchpress", title = "Bench press", sport = "powerlifting",
        info = "A core horizontal strength exercise. It works the chest, triceps and front delts. Perfect for measuring power and progression.\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, guaranteeing equality and transparency in the ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_PressBanca.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• Feet fully planted on the floor.\n• Glutes always in contact with the bench.\n• The bar must come down until it touches the chest.\n• Pause of at least 1 second on the chest.\n• Press up with full arm extension.\n• Grip with index fingers no more than 81 cm apart.\n• It must be a single maximum repetition (1RM), without assistance."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one (same end, separated, with sound).\n2. Show the weight on the end of the bar.\n3. Record the full lift from a side-diagonal angle."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 49 kg (108 lbs)\n• Noob: 50-79 kg (110-174 lbs)\n• Intermediate: 80-109 kg (176-240 lbs)\n• Advanced: 110-129 kg (243-284 lbs)\n• Elite: more than 130 kg (287 lbs)\n\n**Points score**\n• Beginner: up to 45 Points\n• Noob: 46-65 Points\n• Intermediate: 66-85 Points\n• Advanced: 86-100 Points\n• Elite: more than 101 Points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 24 kg (53 lbs)\n• Noob: 25-39 kg (55-86 lbs)\n• Intermediate: 40-59 kg (88-130 lbs)\n• Advanced: 60-79 kg (132-174 lbs)\n• Elite: more than 80 kg (176 lbs)\n\n**Points score**\n• Beginner: up to 35 Points\n• Noob: 36-55 Points\n• Intermediate: 56-75 Points\n• Advanced: 76-95 Points\n• Elite: more than 96 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "deadlift", title = "Deadlift", sport = "powerlifting",
        info = "An essential exercise for developing total strength. It mainly activates the glutes, hamstrings and lower back, and also involves the core, lats and forearms.\n\nIt is one of the best indicators of functional strength and overall power.\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, ensuring equality, technique and safety.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_PesoMuerto.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• Feet fully planted on the floor.\n• Back straight throughout the movement.\n• The bar must start from the floor.\n• Full extension of hips and knees at the end.\n• You may drop the bar when you finish.\n• No external assistance.\n• Only one valid repetition (1RM)."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one from the same end, slightly separated and with audible contact (sound).\n2. Show the weight engraved on the end of the bar.\n3. Record from the side or diagonal, ensuring clear visibility of:\n   - The position of the feet.\n   - The posture of the back.\n   - The full range of motion."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 69 kg (152 lbs)\n• Noob: 70-119 kg (154-262 lbs)\n• Intermediate: 120-159 kg (265-351 lbs)\n• Advanced: 160-189 kg (353-417 lbs)\n• Elite: more than 190 kg (419 lbs)\n\n**Points score**\n• Beginner: up to 60 Points\n• Noob: 61-85 Points\n• Intermediate: 86-105 Points\n• Advanced: 106-120 Points\n• Elite: more than 121 Points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 39 kg (86 lbs)\n• Noob: 40-69 kg (88-152 lbs)\n• Intermediate: 70-99 kg (154-218 lbs)\n• Advanced: 100-129 kg (220-284 lbs)\n• Elite: more than 130 kg (287 lbs)\n\n**Points score**\n• Beginner: up to 45 Points\n• Noob: 46-70 Points\n• Intermediate: 71-95 Points\n• Advanced: 96-115 Points\n• Elite: more than 116 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "sumoDeadlift", title = "Sumo Deadlift", sport = "powerlifting",
        info = "A deadlift variation with a wide foot stance. Ideal for tall people or those with mobility limitations.\n\nIt activates the glutes, quads, adductors, hamstrings, traps and lower back, with a more vertical pattern and less lumbar stress.\n\nAll of these criteria are required to validate an official repetition (1RM) on HitBosss, promoting fair technique, control and transparency.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/Hit_PesoMuertoSumo.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• Wide feet (sumo stance), well planted.\n• Knees pointing outward.\n• Back straight at all times.\n• The bar must start from the floor.\n• Full extension of hips and knees at the end.\n• You may drop the bar when you finish.\n• A single maximum repetition (1RM), without assistance."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one from the same side, separated and with sound.\n2. Show the weight engraved on the end of the bar.\n3. Record from a side or diagonal angle, where you can clearly see:\n   - The width of the stance.\n   - The alignment of the knees and back.\n   - The completion of the lift."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 79 kg (174 lbs)\n• Noob: 80-129 kg (176-284 lbs)\n• Intermediate: 130-169 kg (287-373 lbs)\n• Advanced: 170-199 kg (375-439 lbs)\n• Elite: more than 200 kg (441 lbs)\n\n**Points score**\n• Beginner: up to 65 Points\n• Noob: 66-90 Points\n• Intermediate: 91-110 Points\n• Advanced: 111-125 Points\n• Elite: more than 126 Points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 44 kg (97 lbs)\n• Noob: 45-74 kg (99-163 lbs)\n• Intermediate: 75-104 kg (165-229 lbs)\n• Advanced: 105-134 kg (231-295 lbs)\n• Elite: more than 135 kg (298 lbs)\n\n**Points score**\n• Beginner: up to 45 Points\n• Noob: 46-72 Points\n• Intermediate: 73-98 Points\n• Advanced: 99-118 Points\n• Elite: more than 119 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "officialCrossfit", title = "CrossHIT", sport = "crossfit",
        info = "Since our community is not mostly made up of athletes competing at a professional level, we have adjusted the thresholds to make them more accessible and motivating.\n\nThis ensures that the highest levels are not left empty and that there is clear, achievable progression for all users.",
        videoUrl = null,
        sections = listOf(
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 129 kg (284 lbs)\n• Noob: 130-209 kg (287-461 lbs)\n• Intermediate: 210-289 kg (463-637 lbs)\n• Advanced: 290-359 kg (639-791 lbs)\n• Elite: more than 360 kg (794 lbs)\n\n**Points score**\n• Beginner: up to 109 points\n• Noob: 110-159 points\n• Intermediate: 160-209 points\n• Advanced: 210-259 points\n• Elite: more than 260 points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 79 kg (174 lbs)\n• Noob: 80-139 kg (176-306 lbs)\n• Intermediate: 140-199 kg (309-439 lbs)\n• Advanced: 200-249 kg (441-549 lbs)\n• Elite: more than 250 kg (551 lbs)\n\n**Points score**\n• Beginner: up to 99 points\n• Noob: 100-149 points\n• Intermediate: 150-199 points\n• Advanced: 200-239 points\n• Elite: more than 240 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "snatch", title = "Snatch", sport = "crossfit",
        info = "The Snatch is the Olympic lift in which the bar is raised from the floor to a locked-out position overhead in a single continuous movement.\n\nIt assesses explosive power, shoulder/hip/ankle mobility, coordination and the ability to receive the bar in a low position (overhead squat).\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, ensuring fairness, safety and real competition in the ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_Snatch.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• Starting position: the bar starts from the floor, feet at hip width and a wide grip, neutral back and shoulders slightly in front of the bar.\n• Continuous lift: raise the bar in a single fluid movement, always keeping it close to the body.\n• Body extension: during the pull, fully extend hips, knees and ankles to drive the bar (triple extension).\n• Reception: receive the bar overhead with the arms fully extended and the bar aligned over the center of the body.\n• Stability: control the bar and keep your balance in the overhead position.\n• Finish: stand up with hips and knees locked and arms firm overhead."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one, on the same side, separated from each other and with sound.\n2. Clearly show the weight engraved on the end of the bar.\n3. Record the execution from a diagonal angle, where you can clearly see:\n    - The full lift from the floor to overhead.\n    - The overhead reception of the bar, with the arms fully locked.\n    - The stability and control of the bar before finishing the rep.\n    - The final upright position, with hips and knees fully extended."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 39 kg (86 lbs)\n• Noob: 40-59 kg (88-130 lbs)\n• Intermediate: 60-79 kg (132-174 lbs)\n• Advanced: 80-99 kg (176-218 lbs)\n• Elite: more than 100 kg (220 lbs)\n\n**Points score**\n• Beginner: up to 30 points\n• Noob: 31-45 points\n• Intermediate: 46-60 points\n• Advanced: 61-71 points\n• Elite: more than 72 points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 24 kg (53 lbs)\n• Noob: 25-39 kg (55-86 lbs)\n• Intermediate: 40-54 kg (88-119 lbs)\n• Advanced: 55-69 kg (121-152 lbs)\n• Elite: more than 70 kg (154 lbs)\n\n**Points score**\n• Beginner: up to 26 points\n• Noob: 27-40 points\n• Intermediate: 41-56 points\n• Advanced: 57-70 points\n• Elite: more than 71 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "clean", title = "Clean", sport = "crossfit",
        info = "The Clean is the lift in which the bar is raised from the floor to the shoulders in a single continuous movement, usually received in a deep front squat (overhead squat not included).\n\nIt assesses explosive power, coordination, hip and ankle mobility, and the ability to transfer force from the lower body to the upper body.\nIt differs from the Clean & Jerk in that only the first phase is performed, i.e. from the floor to the shoulders.\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, ensuring fairness, safety and real competition in the ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_Clean.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "• The bar starts from the floor, feet at hip width, medium grip.\n• Fluid, continuous lift up to the shoulders.\n• Full extension of hips, knees and ankles to generate drive.\n• Reception in a deep front squat, high elbows and upright torso.\n• Full control of the bar before completing the rep.\n• Stand up fully, with hips and knees locked."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one, separated and with sound.\n2. Clearly show the weight on the bar.\n3. Record from a diagonal angle where you can see:\n    - The bar from the floor to the shoulders.\n    - A stable reception in the front squat.\n    - Full extension and control of the lift.\n    - The final upright position, with hips and knees locked."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 44 kg (97 lbs)\n• Noob: 45-74 kg (99-163 lbs)\n• Intermediate: 75-104 kg (165-229 lbs)\n• Advanced: 105-129 kg (231-284 lbs)\n• Elite: more than 130 kg (287 lbs)\n\n**Points score**\n• Beginner: up to 35 points\n• Noob: 36-50 points\n• Intermediate: 51-70 points\n• Advanced: 71-85 points\n• Elite: more than 86 points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 24 kg (52 lbs)\n• Noob: 25-44 kg (55-97 lbs)\n• Intermediate: 45-64 kg (99-141 lbs)\n• Advanced: 65-79 kg (143-174 lbs)\n• Elite: more than 80 kg (176 lbs)\n\n**Points score**\n• Beginner: up to 28 points\n• Noob: 29-49 points\n• Intermediate: 50-64 points\n• Advanced: 65-85 points\n• Elite: more than 86 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "cleanAndJerk", title = "Clean & Jerk", sport = "crossfit",
        info = "The Clean & Jerk is the Olympic lift in which the bar is raised from the floor to the shoulders (Clean) and then from the shoulders to a locked-out position overhead (Jerk), in two consecutive, controlled phases.\n\nIt assesses total strength, explosive power, coordination, overhead stability and the ability to transfer force from the lower body to the upper body.\n\nIt is the lift that allows you to move the most absolute load within CrossHIT and weightlifting.\n\nThese criteria are mandatory to validate your rep as an official 1RM on HitBosss, ensuring fairness, safety and real competition in the ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_CleanAndJerk.mp4",
        sections = listOf(
            TutorialSection("✅ How to perform the exercise (1RM)", "Starting position:\n    • The bar starts from the floor, with feet at hip width, a medium grip and a neutral back.\n    • The shoulders are positioned slightly in front of the bar.\n\nClean:\n    • Raise the bar from the floor in a continuous movement, keeping it close to the body.\n    • The bar is received on the shoulders in a stable front-rack position, with high elbows and an upright chest.\n    • The reception can be a power clean or a front squat.\n\nMandatory control:\n    • Before starting the jerk, the athlete must stand up fully and stabilize the bar on the shoulders.\n    • Starting the jerk from an unstable or moving position is not allowed.\n\nJerk:\n    • From the standing position, perform a short, vertical knee bend and drive explosively with the legs, taking the bar overhead.\n    • The drive must come mainly from the lower body, not the arms.\n\nOverhead lockout:\n    • The rep will only be valid if the bar is received with the arms fully extended, stable wrists and the bar aligned over the center of the body.\n\nFinal stability:\n    • There must be clear control of the bar overhead, without excessive steps, imbalances or continuous movements.\n\nFinish:\n    • The lift ends with the athlete upright, with hips and knees locked and the bar firm overhead."),
            TutorialSection("🎥 How to record the exercise", "1. Show the plates one by one, on the same side, separated from each other and with sound.\n2. Clearly show the weight engraved on the end of the bar.\n3. Record the execution from a diagonal angle, where you can clearly see:\n    - The full lift from the floor to the shoulders (Clean).\n    - The stable front position before the Jerk.\n    - The drive and overhead lockout of the Jerk.\n    - The final upright position, with arms, hips and knees fully extended."),
            TutorialSection("💪🏻 Thresholds (Levels)", "👦🏻 **MALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 49 kg (108 lbs)\n• Noob: 50-79 kg (110-174 lbs)\n• Intermediate: 80-109 kg (176-240 lbs)\n• Advanced: 110-139 kg (243-306 lbs)\n• Elite: more than 140 kg (309 lbs)\n\n**Points score**\n• Beginner: up to 40 points\n• Noob: 41-56 points\n• Intermediate: 57-75 points\n• Advanced: 76-92 points\n• Elite: more than 93 points\n\n👩🏼 **FEMALE**\n\n**Lift in kg (lbs)**\n• Beginner: up to 29 kg (64 lbs)\n• Noob: 30-49 kg (66-108 lbs)\n• Intermediate: 50-69 kg (110-152 lbs)\n• Advanced: 70-89 kg (154-196 lbs)\n• Elite: more than 90 kg (198 lbs)\n\n**Points score**\n• Beginner: up to 34 points\n• Noob: 35-54 points\n• Intermediate: 55-74 points\n• Advanced: 75-94 points\n• Elite: more than 95 points"),
        ),
    ),
)
