package com.hitbosss.presentation.feature.settings


/** Contenido de los tutoriales (generado del iOS: ExerciseType+UI + Tutorials.xcstrings). */
data class TutorialSection(val title: String, val body: String)
data class TutorialExercise(
    val apiKey: String, val title: String, val sport: String,
    val info: String, val videoUrl: String?, val sections: List<TutorialSection>,
)

/** Selecciona el contenido por idioma (en/es). iOS solo tiene es; el inglés es traducción propia. */
@androidx.compose.runtime.Composable
fun rememberTutorialData(): List<TutorialExercise> {
    val isEnglish = androidx.compose.ui.platform.LocalConfiguration.current.locales[0].language == "en"
    return if (isEnglish) tutorialDataEn else tutorialDataEs
}

val tutorialDataEs: List<TutorialExercise> = listOf(
    TutorialExercise(
        apiKey = "officialPowerlifting", title = "Powerlifting", sport = "powerlifting",
        info = "Dado que nuestra comunidad no está compuesta mayoritariamente por atletas que compiten a nivel profesional, hemos ajustado los umbrales para que sean más accesibles y motivadores.\n\nEsto asegura que los niveles más altos no queden vacíos y que haya una progresión clara y alcanzable para todos los usuarios.",
        videoUrl = null,
        sections = listOf(
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **MASCULINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 229 kg (505 lbs)\n• Novato: 230–339 kg (507–747 lbs)\n• Medio: 340–409 kg (750–902 lbs)\n• Avanzado: 410 – 489 kg (904–1078 lbs)\n• Élite: 490 kg o más (1080 lbs o más)\n\n**Puntuación Points**\n• Principiante: hasta 139 puntos\n• Novato: 140-209 puntos\n• Medio: 210-269 puntos\n• Avanzado: 270-319 puntos\n• Élite: más de 320 puntos\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 99 kg (218 lbs)\n• Novato: 100–169 kg (220–373 lbs)\n• Medio: 170–249 kg (375–549 lbs)\n• Avanzado: 250–329 kg (551–725 lbs)\n• Élite: 330 kg o más (728 lbs o más)\n\n**Puntuación Points**\n• Principiante: hasta 119 puntos\n• Novato: 120-189 puntos\n• Medio: 190-259 puntos\n• Avanzado: 260-319 puntos\n• Élite: más de 320 puntos"),
        ),
    ),
    TutorialExercise(
        apiKey = "squat", title = "Sentadilla", sport = "powerlifting",
        info = "Ejercicio fundamental para desarrollar fuerza en el tren inferior. Involucra principalmente cuádriceps, glúteos, y también activa isquios y core.\n\nPerfecto para medir potencia, movilidad y control corporal.\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, asegurando justicia, seguridad y competencia real en el ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_Sentadilla.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• Pies totalmente apoyados en el suelo.\n• Espalda recta durante todo el movimiento.\n• La cadera debe romper el paralelo (bajar por debajo de la línea de las rodillas).\n• Extensión completa al subir (caderas y rodillas bloqueadas al final).\n• Barra colocada sobre los trapecios o deltoides posteriores (según variante).\n• No se permite ayuda externa.\n• Debe ser una única repetición máxima (1RM)."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar los discos uno a uno (mismo lado, separados entre sí y con sonido).\n2. Enseñar el peso grabado en el extremo de la barra.\n3. Grabar ejecución desde un ángulo lateral o diagonal, donde se vea claramente:\n   - La profundidad del movimiento.\n   - La colocación de la barra.\n   - El rango completo del levantamiento."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **MASCULINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 59 kg (130 lbs)\n• Novato: 60-99 kg (132-218 lbs)\n• Medio: 100-139 kg (220-306 lbs)\n• Avanzado: 140-169 kg (309-373 lbs)\n• Élite: más de 170 kg (375 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 55 Points\n• Novato: 56-75 Points\n• Medio: 76-95 Points\n• Avanzado: 96-110 Points\n• Élite: más de 111 Points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 34 kg (75 lbs)\n• Novato: 35-59 kg (77-130 lbs)\n• Medio: 60-89 kg (132-196 lbs)\n• Avanzado: 90-119 kg (198-262 lbs)\n• Élite: más de 120 kg (265 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 40 Points\n• Novato: 41-65 Points\n• Medio: 66-90 Points\n• Avanzado: 91-110 Points\n• Élite: más de 111 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "benchpress", title = "Press banca", sport = "powerlifting",
        info = "Ejercicio base de fuerza horizontal. Trabaja pecho, tríceps y deltoides anteriores. Perfecto para medir potencia y progresión.\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, garantizando igualdad y transparencia en el ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_PressBanca.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• Pies totalmente apoyados en el suelo.\n• Glúteos siempre en contacto con el banco.\n• La barra debe bajar hasta tocar el pecho.\n• Pausa de al menos 1 segundo en el pecho.\n• Subida con extensión completa de brazos.\n• Agarre con índices a máximo 81 cm de distancia.\n• Debe ser una sola repetición máxima (1RM), sin ayuda."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar discos uno a uno (mismo extremo, separados, con sonido).\n2. Enseñar el peso del extremo de la barra.\n3. Grabar levantamiento de perfil-diagonal completo."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **MASCULINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 49 kg (108 lbs)\n• Novato: 50-79 kg (110-174 lbs)\n• Medio: 80-109 kg (176-240 lbs)\n• Avanzado: 110-129 kg (243-284 lbs)\n• Élite: más de 130 kg (287 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 45 Points\n• Novato: 46-65 Points\n• Medio: 66-85 Points\n• Avanzado: 86-100 Points\n• Élite: más de 101 Points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 24 kg (53 lbs)\n• Novato: 25-39 kg (55-86 lbs)\n• Medio: 40-59 kg (88-130 lbs)\n• Avanzado: 60-79 kg (132-174 lbs)\n• Élite: más de 80 kg (176 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 35 Points\n• Novato: 36-55 Points\n• Medio: 56-75 Points\n• Avanzado: 76-95 Points\n• Élite: más de 96 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "deadlift", title = "Peso muerto", sport = "powerlifting",
        info = "Ejercicio esencial para el desarrollo de fuerza total. Activa principalmente glúteos, isquios y zona lumbar, además de implicar core, dorsales y antebrazos.\n\nEs uno de los mejores indicadores de fuerza funcional y potencia general.\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, asegurando igualdad, técnica y seguridad.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/HIT_PesoMuerto.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• Pies completamente apoyados en el suelo.\n• Espalda recta durante todo el movimiento.\n• La barra debe partir desde el suelo.\n• Extensión completa de caderas y rodillas al finalizar.\n• Permitido soltar la barra al terminar.\n• Sin asistencia externa.\n• Solo una repetición válida (1RM)."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar los discos uno a uno desde el mismo extremo, ligeramente separados y con contacto audible (sonido).\n2. Enseñar el peso grabado en el extremo de la barra.\n3. Grabar desde perfil o diagonal, asegurando visibilidad clara de:\n   - Posición de los pies.\n   - Postura de espalda.\n   - Rango completo de movimiento."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **MASCULINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 69 kg (152 lbs)\n• Novato: 70-119 kg (154-262 lbs)\n• Medio: 120-159 kg (265-351 lbs)\n• Avanzado: 160-189 kg (353-417 lbs)\n• Élite: más de 190 kg (419 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 60 Points\n• Novato: 61-85 Points\n• Medio: 86-105 Points\n• Avanzado: 106-120 Points\n• Élite: más de 121 Points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 39 kg (86 lbs)\n• Novato: 40-69 kg (88-152 lbs)\n• Medio: 70-99 kg (154-218 lbs)\n• Avanzado: 100-129 kg (220-284 lbs)\n• Élite: más de 130 kg (287 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 45 Points\n• Novato: 46-70 Points\n• Medio: 71-95 Points\n• Avanzado: 96-115 Points\n• Élite: más de 116 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "sumoDeadlift", title = "Peso muerto sumo", sport = "powerlifting",
        info = "Variante del peso muerto con posición amplia de pies. Ideal para personas altas o con limitaciones de movilidad.\n\nActiva glúteos, cuádriceps, aductores, isquios, trapecios y zona lumbar, con un patrón más vertical y menor estrés lumbar.\n\nTodos estos criterios son necesarios para validar una repetición oficial (1RM) en HitBosss, promoviendo técnica justa, control y transparencia.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/Hit_PesoMuertoSumo.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• Pies abiertos (posición sumo), bien apoyados.\n• Rodillas apuntando hacia fuera.\n• Espalda recta en todo momento.\n• La barra debe partir desde el suelo.\n• Extensión completa de caderas y rodillas al finalizar.\n• Permitido soltar la barra al finalizar.\n• Una única repetición máxima (1RM), sin ayuda."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar discos uno a uno desde el mismo lado, separados y con sonido.\n2. Enseñar peso grabado en el extremo de la barra.\n3. Grabar desde ángulo lateral o diagonal, donde se vea con claridad:\n   - Apertura de piernas.\n   - Alineación de rodillas y espalda.\n   - Finalización del levantamiento."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **MASCULINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 79 kg (174 lbs)\n• Novato: 80-129 kg (176-284 lbs)\n• Medio: 130-169 kg (287-373 lbs)\n• Avanzado: 170-199 kg (375-439 lbs)\n• Élite: más de 200 kg (441 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 65 Points\n• Novato: 66-90 Points\n• Medio: 91-110 Points\n• Avanzado: 111-125 Points\n• Élite: más de 126 Points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kilos (libras)**\n• Principiante: hasta 44 kg (97 lbs)\n• Novato: 45-74 kg (99-163 lbs)\n• Medio: 75-104 kg (165-229 lbs)\n• Avanzado: 105-134 kg (231-295 lbs)\n• Élite: más de 135 kg (298 lbs)\n\n**Puntuación Points**\n• Principiante: hasta 45 Points\n• Novato: 46-72 Points\n• Medio: 73-98 Points\n• Avanzado: 99-118 Points\n• Élite: más de 119 Points"),
        ),
    ),
    TutorialExercise(
        apiKey = "officialCrossfit", title = "CrossHIT", sport = "crossfit",
        info = "Dado que nuestra comunidad no está compuesta mayoritariamente por atletas que compiten a nivel profesional, hemos ajustado los umbrales para que sean más accesibles y motivadores.\n\nEsto asegura que los niveles más altos no queden vacíos y que haya una progresión clara y alcanzable para todos los usuarios.",
        videoUrl = null,
        sections = listOf(
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **VARONIL**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 129 kg (284 lbs)\n• Novato: 130-209 kg (287-461 lbs)\n• Medio: 210-289 kg (463-637 lbs)\n• Avanzado: 290-359 kg (639-791 lbs)\n• Élite: más de 360 kg (794 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 109 points\n• Novato: 110-159 points\n• Medio: 160-209 points\n• Avanzado: 210-259 points\n• Élite: más de 260 points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 79 kg (174 lbs)\n• Novato: 80-139 kg (176-306 lbs)\n• Medio: 140-199 kg (309-439 lbs)\n• Avanzado: 200-249 kg (441-549 lbs)\n• Élite: más de 250 kg (551 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 99 points\n• Novato: 100-149 points\n• Medio: 150-199 points\n• Avanzado: 200-239 points\n• Élite: más de 240 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "snatch", title = "Snatch", sport = "crossfit",
        info = "El Snatch es el levantamiento olímpico en el que la barra se eleva del suelo hasta el bloqueo de brazos por encima de la cabeza en un solo movimiento continuo.\n\nEvalúa potencia explosiva, movilidad de hombros/caderas/tobillos, coordinación y la capacidad de recibir la barra en posición baja (overhead squat).\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, asegurando justicia, seguridad y competencia real en el ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_Snatch.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• Posición inicial: la barra parte desde el suelo, con los pies a la anchura de las caderas y agarre amplio, espalda neutra y hombros ligeramente por delante de la barra.\n• Levantamiento continuo: eleva la barra en un solo movimiento fluido, manteniéndola siempre cerca del cuerpo.\n• Extensión del cuerpo: durante la subida, extiende completamente caderas, rodillas y tobillos para impulsar la barra (triple extensión).\n• Recepción: recibe la barra por encima de la cabeza con los brazos completamente extendidos y la barra alineada sobre el centro del cuerpo.\n• Estabilidad: controla la barra y mantén el equilibrio en posición overhead.\n• Finalización: ponte de pie con caderas y rodillas bloqueadas y brazos firmes sobre la cabeza."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar los discos uno a uno, en el mismo lado, separados entre sí y con sonido.\n2. Enseñar claramente el peso grabado en el extremo de la barra.\n3. Grabar la ejecución desde un ángulo diagonal, donde se vea con claridad:\n    - El levantamiento completo del suelo hasta por encima de la cabeza.\n    - La recepción de la barra overhead, con los brazos totalmente bloqueados.\n    - La estabilidad y control de la barra antes de finalizar la repetición.\n    - La posición final erguida, con caderas y rodillas completamente extendidas."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **VARONIL**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 39 kg (86 lbs)\n• Novato: 40-59 kg (88-130 lbs)\n• Medio: 60-79 kg (132-174 lbs)\n• Avanzado: 80-99 kg (176-218 lbs)\n• Élite: más de 100 kg (220 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 30 points\n• Novato: 31-45 points\n• Medio: 46-60 points\n• Avanzado: 61-71 points\n• Élite: más de 72 points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 24 kg (53 lbs)\n• Novato: 25-39 kg (55-86 lbs)\n• Medio: 40-54 kg (88-119 lbs)\n• Avanzado: 55-69 kg (121-152 lbs)\n• Élite: más de 70 kg (154 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 26 points\n• Novato: 27-40 points\n• Medio: 41-56 points\n• Avanzado: 57-70 points\n• Élite: más de 71 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "clean", title = "Clean", sport = "crossfit",
        info = "El Clean es el levantamiento en el que la barra se eleva del suelo hasta los hombros en un solo movimiento continuo, recibiéndola generalmente en sentadilla frontal profunda (overhead squat no incluido).\n\nEvalúa potencia explosiva, coordinación, movilidad de caderas y tobillos, y la capacidad de transferir fuerza desde el tren inferior al superior.\nSe diferencia del Clean & Jerk en que solo se realiza la primera fase, es decir, del suelo hasta los hombros.\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, asegurando justicia, seguridad y competencia real en el ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_Clean.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "• La barra parte desde el suelo, pies a la anchura de las caderas, agarre medio.\n• Levantamiento fluido y continuo hasta los hombros.\n• Extensión completa de cadera, rodillas y tobillos para generar impulso.\n• Recepción en sentadilla frontal profunda, codos altos y torso erguido.\n• Control total de la barra antes de completar la repetición.\n• Ponerse de pie completamente, con caderas y rodillas bloqueadas."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar los discos uno a uno, separados y con sonido.\n2. Enseñar el peso de la barra claramente.\n3. Grabar desde un ángulo diagonal donde se vea:\n    - La barra desde el suelo hasta los hombros.\n    - Recepción estable en sentadilla frontal.\n    - Extensión completa y control del levantamiento.\n    - Posición final erguida, con caderas y rodillas bloqueadas."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **VARONIL**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 44 kg (97 lbs)\n• Novato: 45-74 kg (99-163 lbs)\n• Medio: 75-104 kg (165-229 lbs)\n• Avanzado: 105-129 kg (231-284 lbs)\n• Élite: más de 130 kg (287 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 35 points\n• Novato: 36-50 points\n• Medio: 51-70 points\n• Avanzado: 71-85 points\n• Élite: más de 86 points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 24 kg (52 lbs)\n• Novato: 25-44 kg (55-97 lbs)\n• Medio: 45-64 kg (99-141 lbs)\n• Avanzado: 65-79 kg (143-174 lbs)\n• Élite: más de 80 kg (176 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 28 points\n• Novato: 29-49 points\n• Medio: 50-64 points\n• Avanzado: 65-85 points\n• Élite: más de 86 points"),
        ),
    ),
    TutorialExercise(
        apiKey = "cleanAndJerk", title = "Clean & Jerk", sport = "crossfit",
        info = "El Clean & Jerk es el levantamiento olímpico en el que la barra se eleva del suelo hasta los hombros (Clean) y posteriormente desde los hombros hasta el bloqueo de brazos por encima de la cabeza (Jerk), en dos fases consecutivas y controladas.\n\nEvalúa fuerza total, potencia explosiva, coordinación, estabilidad overhead y la capacidad de transferir fuerza del tren inferior al superior.\n\nEs el levantamiento que permite mover más carga absoluta dentro de CrossHIT y halterofilia.\n\nEstos criterios son obligatorios para validar tu repetición como 1RM oficial en HitBosss, asegurando justicia, seguridad y competencia real en el ranking.",
        videoUrl = "https://hitbosss-media.s3.eu-south-2.amazonaws.com/video_tutoriales/CF_CleanAndJerk.mp4",
        sections = listOf(
            TutorialSection("✅ Cómo realizar el ejercicio (1RM)", "Posición inicial:\n    • La barra parte desde el suelo, con los pies a la anchura de las caderas, agarre medio y espalda neutra.\n    • Los hombros se sitúan ligeramente por delante de la barra.\n\nClean:\n    • Eleva la barra desde el suelo en un movimiento continuo, manteniéndola cerca del cuerpo.\n    • La barra se recibe sobre los hombros en una posición estable de front rack, con los codos altos y el pecho erguido.\n    • La recepción puede ser en power clean o sentadilla frontal.\n\nControl obligatorio:\n    • Antes de iniciar el jerk, el atleta debe ponerse completamente de pie y estabilizar la barra sobre los hombros.\n    • No se permite iniciar el jerk desde una posición inestable o en movimiento.\n\nJerk:\n    • Desde la posición de pie, realiza una flexión corta y vertical de rodillas y empuja de forma explosiva con las piernas, llevando la barra por encima de la cabeza.\n    • El impulso debe venir principalmente del tren inferior, no de los brazos.\n\nBloqueo overhead:\n    • La repetición solo será válida si la barra se recibe con los brazos completamente extendidos, muñecas estables y la barra alineada sobre el centro del cuerpo.\n\nEstabilidad final:\n    • Debe existir control claro de la barra overhead, sin pasos excesivos, desequilibrios ni movimientos continuos.\n\nEstabilidad final:\n    • Debe existir control claro de la barra overhead, sin pasos excesivos, desequilibrios ni movimientos continuos.\n\nFinalización:\n    • El levantamiento finaliza con el atleta erguido, con caderas y rodillas bloqueadas y la barra firme por encima de la cabeza."),
            TutorialSection("🎥 Cómo grabar el ejercicio", "1. Mostrar los discos uno a uno, en el mismo lado, separados entre sí y con sonido.\n2. Enseñar claramente el peso grabado en el extremo de la barra.\n3. Grabar la ejecución desde un ángulo diagonal, donde se vea con claridad:\n    - El levantamiento completo del suelo a los hombros (Clean).\n    - La posición frontal estable antes del Jerk.\n    - El empuje y bloqueo overhead del Jerk.\n    - La posición final erguida, con brazos, caderas y rodillas completamente extendidos."),
            TutorialSection("💪🏻 Umbrales (Niveles)", "👦🏻 **VARONIL**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 49 kg (108 lbs)\n• Novato: 50-79 kg (110-174 lbs)\n• Medio: 80-109 kg (176-240 lbs)\n• Avanzado: 110-139 kg (243-306 lbs)\n• Élite: más de 140 kg (309 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 40 points\n• Novato: 41-56 points\n• Medio: 57-75 points\n• Avanzado: 76-92 points\n• Élite: más de 93 points\n\n👩🏼 **FEMENINO**\n\n**Levantamiento en kgs (lbs)**\n• Principiante: hasta 29 kg (64 lbs)\n• Novato: 30-49 kg (66-108 lbs)\n• Medio: 50-69 kg (110-152 lbs)\n• Avanzado: 70-89 kg (154-196 lbs)\n• Élite: más de 90 kg (198 lbs)\n\n**Puntuación (Points)**\n• Principiante: hasta 34 points\n• Novato: 35-54 points\n• Medio: 55-74 points\n• Avanzado: 75-94 points\n• Élite: más de 95 points"),
        ),
    ),
)
